# Generated by Django 6.0.5 on 2026-05-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_job_id_application'),
        ('core', '0002_user_company'),
    ]

    operations = [
    ]
