# Generated by Django 6.0.5 on 2026-05-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_alter_job_id_application_0002_user_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
